CRITICAL - 2023-12-05 19:10:03 --> Invalid file: "welcome_message2.php"
in SYSTEMPATH/Exceptions/FrameworkException.php on line 39.
 1 SYSTEMPATH/View/View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('welcome_message2.php')
 2 SYSTEMPATH/Common.php(1190): CodeIgniter\View\View->render('welcome_message2', [], true)
 3 APPPATH/Controllers/Home.php(9): view('welcome_message2')
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Home->index()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-05 19:31:14 --> Invalid file: "login.php"
in SYSTEMPATH/Exceptions/FrameworkException.php on line 39.
 1 SYSTEMPATH/View/View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
 2 SYSTEMPATH/Common.php(1190): CodeIgniter\View\View->render('login', [], true)
 3 APPPATH/Controllers/Home.php(8): view('login')
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Home->index()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-05 19:40:08 --> Class 'App\Models\UserModel' not found
in APPPATH/Controllers/Home.php on line 10.
 1 SYSTEMPATH/CodeIgniter.php(914): App\Controllers\Home->__construct()
 2 SYSTEMPATH/CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-05 19:40:10 --> Class 'App\Models\UserModel' not found
in APPPATH/Controllers/Home.php on line 10.
 1 SYSTEMPATH/CodeIgniter.php(914): App\Controllers\Home->__construct()
 2 SYSTEMPATH/CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-05 19:40:23 --> Class 'App\Models\UserModel' not found
in APPPATH/Controllers/Home.php on line 10.
 1 SYSTEMPATH/CodeIgniter.php(914): App\Controllers\Home->__construct()
 2 SYSTEMPATH/CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-05 19:40:24 --> Class 'App\Models\UserModel' not found
in APPPATH/Controllers/Home.php on line 10.
 1 SYSTEMPATH/CodeIgniter.php(914): App\Controllers\Home->__construct()
 2 SYSTEMPATH/CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-05 19:42:08 --> Class 'App\Models\UserModel' not found
in APPPATH/Controllers/Home.php on line 10.
 1 SYSTEMPATH/CodeIgniter.php(914): App\Controllers\Home->__construct()
 2 SYSTEMPATH/CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-05 19:42:35 --> Namespace declaration statement has to be the very first statement or after any declare call in the script
in APPPATH/Models/ModelLogin.php on line 4.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-12-05 19:42:44 --> Namespace declaration statement has to be the very first statement or after any declare call in the script
in APPPATH/Models/ModelLogin.php on line 4.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-12-05 19:42:47 --> Namespace declaration statement has to be the very first statement or after any declare call in the script
in APPPATH/Models/ModelLogin.php on line 4.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-12-05 19:43:21 --> Namespace declaration statement has to be the very first statement or after any declare call in the script
in APPPATH/Models/ModelLogin.php on line 4.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-12-05 19:44:01 --> Namespace declaration statement has to be the very first statement or after any declare call in the script
in APPPATH/Models/ModelLogin.php on line 4.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2023-12-05 19:56:05 --> Error connecting to the database: ErrorException: oci_connect(): ORA-12154: TNS:could not resolve the connect identifier specified in /var/www/html/app_clinica/system/Database/OCI8/Connection.php:129
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_connect(): ...', '/var/www/html/a...', 129, Array)
#1 /var/www/html/app_clinica/system/Database/OCI8/Connection.php(129): oci_connect('ADMIN', 'ssprueba.210', 'oci:dbname=//or...', 'utf8')
#2 /var/www/html/app_clinica/system/Database/BaseConnection.php(392): CodeIgniter\Database\OCI8\Connection->connect(false)
#3 /var/www/html/app_clinica/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 /var/www/html/app_clinica/app/Models/ModelLogin.php(20): CodeIgniter\Database\BaseConnection->query('SELECT 1 FROM d...')
#5 /var/www/html/app_clinica/app/Controllers/Home.php(17): App\Models\ModelLogin->isDbConnected()
#6 /var/www/html/app_clinica/system/CodeIgniter.php(942): App\Controllers\Home->index()
#7 /var/www/html/app_clinica/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 /var/www/html/app_clinica/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /var/www/html/app_clinica/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-12-05 19:56:05 --> Unable to connect to the database.
Main connection [OCI8]: oci_connect(): ORA-12154: TNS:could not resolve the connect identifier specified
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/ModelLogin.php(20): CodeIgniter\Database\BaseConnection->query('SELECT 1 FROM dual')
 3 APPPATH/Controllers/Home.php(17): App\Models\ModelLogin->isDbConnected()
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Home->index()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-05 19:57:03 --> Error connecting to the database: ErrorException: oci_connect(): ORA-12154: TNS:could not resolve the connect identifier specified in /var/www/html/app_clinica/system/Database/OCI8/Connection.php:129
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_connect(): ...', '/var/www/html/a...', 129, Array)
#1 /var/www/html/app_clinica/system/Database/OCI8/Connection.php(129): oci_connect('ADMIN', 'ssprueba.210', 'oci:dbname=//or...', 'utf8')
#2 /var/www/html/app_clinica/system/Database/BaseConnection.php(392): CodeIgniter\Database\OCI8\Connection->connect(false)
#3 /var/www/html/app_clinica/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 /var/www/html/app_clinica/app/Models/ModelLogin.php(20): CodeIgniter\Database\BaseConnection->query('SELECT 1 FROM d...')
#5 /var/www/html/app_clinica/app/Controllers/Home.php(19): App\Models\ModelLogin->isDbConnected()
#6 /var/www/html/app_clinica/system/CodeIgniter.php(942): App\Controllers\Home->index()
#7 /var/www/html/app_clinica/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 /var/www/html/app_clinica/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /var/www/html/app_clinica/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-05 19:57:03 --> Error connecting to the database: ErrorException: oci_connect(): ORA-12154: TNS:could not resolve the connect identifier specified in /var/www/html/app_clinica/system/Database/OCI8/Connection.php:129
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_connect(): ...', '/var/www/html/a...', 129, Array)
#1 /var/www/html/app_clinica/system/Database/OCI8/Connection.php(129): oci_connect('ADMIN', 'ssprueba.210', 'oci:dbname=//or...', 'utf8')
#2 /var/www/html/app_clinica/system/Database/BaseConnection.php(392): CodeIgniter\Database\OCI8\Connection->connect(false)
#3 /var/www/html/app_clinica/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 /var/www/html/app_clinica/app/Models/ModelLogin.php(21): CodeIgniter\Database\BaseConnection->query('SELECT 1 FROM d...')
#5 /var/www/html/app_clinica/app/Controllers/Home.php(17): App\Models\ModelLogin->isDbConnected()
#6 /var/www/html/app_clinica/system/CodeIgniter.php(942): App\Controllers\Home->index()
#7 /var/www/html/app_clinica/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 /var/www/html/app_clinica/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /var/www/html/app_clinica/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-05 19:57:03 --> Error connecting to the database: ErrorException: oci_connect(): ORA-12154: TNS:could not resolve the connect identifier specified in /var/www/html/app_clinica/system/Database/OCI8/Connection.php:129
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_connect(): ...', '/var/www/html/a...', 129, Array)
#1 /var/www/html/app_clinica/system/Database/OCI8/Connection.php(129): oci_connect('ADMIN', 'ssprueba.210', 'oci:dbname=//or...', 'utf8')
#2 /var/www/html/app_clinica/system/Database/BaseConnection.php(392): CodeIgniter\Database\OCI8\Connection->connect(false)
#3 /var/www/html/app_clinica/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 /var/www/html/app_clinica/app/Models/ModelLogin.php(21): CodeIgniter\Database\BaseConnection->query('SELECT 1 FROM d...')
#5 /var/www/html/app_clinica/app/Controllers/Home.php(19): App\Models\ModelLogin->isDbConnected()
#6 /var/www/html/app_clinica/system/CodeIgniter.php(942): App\Controllers\Home->index()
#7 /var/www/html/app_clinica/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 /var/www/html/app_clinica/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /var/www/html/app_clinica/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-12-05 19:57:03 --> Unable to connect to the database.
Main connection [OCI8]: oci_connect(): ORA-12154: TNS:could not resolve the connect identifier specified
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/ModelLogin.php(20): CodeIgniter\Database\BaseConnection->query('SELECT 1 FROM dual')
 3 APPPATH/Controllers/Home.php(19): App\Models\ModelLogin->isDbConnected()
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Home->index()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-05 19:57:03 --> Error connecting to the database: ErrorException: oci_connect(): ORA-12154: TNS:could not resolve the connect identifier specified in /var/www/html/app_clinica/system/Database/OCI8/Connection.php:129
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_connect(): ...', '/var/www/html/a...', 129, Array)
#1 /var/www/html/app_clinica/system/Database/OCI8/Connection.php(129): oci_connect('ADMIN', 'ssprueba.210', 'oci:dbname=//or...', 'utf8')
#2 /var/www/html/app_clinica/system/Database/BaseConnection.php(392): CodeIgniter\Database\OCI8\Connection->connect(false)
#3 /var/www/html/app_clinica/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 /var/www/html/app_clinica/app/Models/ModelLogin.php(15): CodeIgniter\Database\BaseConnection->query('SELECT 1 FROM d...')
#5 /var/www/html/app_clinica/app/Controllers/Home.php(16): App\Models\ModelLogin->test()
#6 /var/www/html/app_clinica/system/CodeIgniter.php(942): App\Controllers\Home->index()
#7 /var/www/html/app_clinica/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 /var/www/html/app_clinica/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /var/www/html/app_clinica/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-12-05 19:57:03 --> Unable to connect to the database.
Main connection [OCI8]: oci_connect(): ORA-12154: TNS:could not resolve the connect identifier specified
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/ModelLogin.php(21): CodeIgniter\Database\BaseConnection->query('SELECT 1 FROM dual')
 3 APPPATH/Controllers/Home.php(19): App\Models\ModelLogin->isDbConnected()
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Home->index()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-05 19:57:03 --> Unable to connect to the database.
Main connection [OCI8]: oci_connect(): ORA-12154: TNS:could not resolve the connect identifier specified
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/ModelLogin.php(21): CodeIgniter\Database\BaseConnection->query('SELECT 1 FROM dual')
 3 APPPATH/Controllers/Home.php(17): App\Models\ModelLogin->isDbConnected()
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Home->index()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-05 19:57:03 --> Unable to connect to the database.
Main connection [OCI8]: oci_connect(): ORA-12154: TNS:could not resolve the connect identifier specified
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/ModelLogin.php(15): CodeIgniter\Database\BaseConnection->query('SELECT 1 FROM dual')
 3 APPPATH/Controllers/Home.php(16): App\Models\ModelLogin->test()
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Home->index()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
